src/components/LocationCards.jsx, src/scss/LocationCards.scss
- **login page styling fixed**
- **menuboard styled**
- **logoutbutton added wherever requested**
- **waiterLogin component rename**
- **Rename waiterLogin.jsx to WaiterLogin.jsx**
- **Rename waiterLogin.jsx to WaiterLogin.jsx**
- **create agent page styled**
- **menu list page styled**
- **location cards landing page styled**
=> landing page styled

src/components/EnhanceMenu.jsx, src/scss/EnhanceMenu.scss
- **Enhance menu first steps added**
- **Backend changes for enhancedmenu**
- **enhance menu styled**
=> enhance page styled

src/components/Visitor Components/DigiMenu.jsx, src/components/Visitor Components/MenuItemCard.jsx, src/scss/DigiMenu.scss, src/scss/variables.scss
- **variables file updated + new scss file (empty)**
- **digimenu styled**
=> digimenu styled with neumorphism

src/components/Visitor Components/Cart.jsx, src/components/Visitor Components/DigiMenu.jsx, src/scss/DigiMenu.scss, src/scss/variables.scss
- **variables file updated + new scss file (empty)**
- **digimenu styled**
- **cart popup styled with animations**
=> cart modal styled  with animations + confirmation modal

src/components/Visitor Components/ConfirmTable.jsx, src/components/Visitor Components/DigiMenu.jsx, src/scss/ConfirmTable.scss, src/scss/DigiMenu.scss, src/scss/animations.scss, src/scss/variables.scss
- **variables file updated + new scss file (empty)**
- **digimenu styled**
- **cart popup styled with animations**
- **confirm table styled + entry animation**
=> confirm table styled + entry animation for digimenu

src/components/Visitor Components/Cart.jsx, src/components/Visitor Components/DigiMenu.jsx, src/components/Visitor Components/MenuItemCard.jsx, src/scss/ConfirmTable.scss
- **digimenu method usage + supported_api small change**
- **new file created + paths updated**
- **fetchMenuItem function created + utilized**
- **shabbiness limited**
- **delay applied on add and subtract cart items**
=> minor fixes

src/components/Visitor Components/MenuItemCard.jsx
- **digimenu method usage + supported_api small change**
- **new file created + paths updated**
- **fetchMenuItem function created + utilized**
- **shabbiness limited**
- **delay applied on add and subtract cart items**
- **fix reverted**
=> fix reverted

src/components/Visitor Components/DigiMenu.jsx, src/components/Visitor Components/MenuItemCard.jsx, src/scss/DigiMenu.scss
- **category wise split of list view**
- **displayType=grid & displayType=row - styles diffed**
=> requested changes done

src/components/Visitor Components/DigiMenu.jsx, src/components/Visitor Components/HighlightBanner.jsx, src/scss/DigiMenu.scss, src/scss/HighlightBanner.scss, src/scss/MenuDetail.scss, src/scss/animations.scss
- **add to cart button placement fixed**
- **highlight banners first commit**
=> highlight banners first commit

src/scss/AddItem.scss, src/scss/AgentHome.scss, src/scss/AlertPopup.scss, src/scss/ConfirmTable.scss, src/scss/CreateAgent.scss, src/scss/CreateOrganization.scss, src/scss/DigiMenu.scss, src/scss/EnhanceMenu.scss, src/scss/HighlightBanner.scss, src/scss/LocationCards.scss, src/scss/LoginScreen.scss, src/scss/LogoutButton.scss, src/scss/MenuDetail.scss, src/scss/MenuList.scss, src/scss/MenuListDashboard.scss, src/scss/WaiterLogin.scss, src/scss/variables.scss, vite.config.js
- **minor fixes**
- **gitignore changes**
- **agent login styled**
- **waiter screens styled and dusted**
- **all warnings cleared**
=> @use instead of @import

src/components/Admin Portal Component/CreateAgent.jsx, src/components/Admin Portal Component/CreateOrganisation.jsx, src/components/Admin Portal Component/LoginScreen.jsx, src/components/Admin Portal Component/MenuList.jsx, src/components/Admin Portal Component/MenuListDashboard.jsx, src/components/Visitor Components/Cart.jsx, src/components/Waiter Portal Components/AgentHome.jsx, src/components/Waiter Portal Components/ConfirmationTable.jsx, src/components/Waiter Portal Components/OrderModal.jsx, src/components/Waiter Portal Components/WaiterLogin.jsx, src/scss/AddItem.scss, src/scss/AgentHome.scss, src/scss/ConfirmTable.scss, src/scss/CreateAgent.scss, src/scss/CreateOrganization.scss, src/scss/DigiMenu.scss, src/scss/EnhanceMenu.scss, src/scss/LocationCards.scss, src/scss/LoginScreen.scss, src/scss/MenuList.scss, src/scss/MenuListDashboard.scss, src/scss/WaiterLogin.scss, src/scss/mixins.scss, src/scss/variables.scss
mixin.scss created to import and define the variables dynamically
themes map defined in variables.scss
throughout all the scss files the hard coded occurrences have been changed to vars
only pending thing is to dynamically assign the classname in js for the specific theme chosen by the user
=> scss theme setup

src/components/Admin Portal Component/CreateQR.jsx, src/components/Admin Portal Component/MenuList.jsx, src/scss/CreateQR.scss, src/scss/MenuList.scss
- **minor fixes**
- **add menu popup styled**
- **createQR styled**
=> styling changes

src/scss/DigiMenu.scss
- **order overlay and thank you screen styled**
- **bg color update**
=> bg color update

src/components/Admin Portal Component/AllAgents.jsx, src/components/Admin Portal Component/LocationSettings.jsx, src/scss/AllAgents.scss, src/scss/LocationSettings.scss, src/scss/variables.scss
- **order overlay and thank you screen styled**
- **bg color update**
- **settings page styled**
- **all agents page styled**
=> settings page and all agents page styled

src/components/Admin Portal Component/AllAgents.jsx, src/scss/AllAgents.scss
- **order overlay and thank you screen styled**
- **bg color update**
- **settings page styled**
- **all agents page styled**
- **all agents styling changes**
=> all agents page styled

src/components/Admin Portal Component/AllAgents.jsx, src/components/Admin Portal Component/CreateQR.jsx, src/components/Admin Portal Component/LocationCards.jsx, src/components/Admin Portal Component/LocationSettings.jsx, src/components/Admin Portal Component/MenuList.jsx, src/components/Admin Portal Component/MenuListDashboard.jsx, src/scss/AllAgents.scss, src/scss/CreateQR.scss, src/scss/LocationCards.scss, src/scss/LocationSettings.scss, src/scss/MenuList.scss, src/scss/MenuListDashboard.scss, src/scss/themes.scss
- **implemented theme for the following components**
- **all agents**
=> scss changes

src/components/Visitor Components/DigiMenu.jsx, src/scss/DigiMenu.scss, src/scss/flatdigimenu.scss
complex class names from Digimenu.jsx removed
digimenu.scss adjusted to handle the removed tailwind styles from the component
implemented a simple logic to load different scss for the same component based on query parameter(temproary soon it will be from backend)
FUCKED UP: CARD styling fucked up while clearing Digmenu.jsx, Highlight banner also slightly fucked up
@mahessh77melo Need to fix them
=> Multi theme for digimenu using query params fr now

src/components/Admin Portal Component/MenuList.jsx, src/components/Visitor Components/Cart.jsx, src/components/Visitor Components/DigiMenu.jsx, src/components/Visitor Components/MenuDetail.jsx, src/components/Visitor Components/MenuItemCard.jsx, src/scss/DigiMenu.scss, src/scss/MenuDetail.scss
styling pending, correct approach figured out
=> quantity component setup

src/components/Visitor Components/MenuDetail.jsx, src/components/Visitor Components/MenuItemCard.jsx, src/scss/DigiMenu.scss, src/scss/MenuDetail.scss
- **changes part 1**
- **quantity component (only by mahesh)**
- **special bug fix (all mahesh)**
- **minor bug fixes + quantity styling**
=> styling fixes + tick mark bug fix

src/scss/MenuDetail.scss
- **changes part 1**
- **quantity component (only by mahesh)**
- **special bug fix (all mahesh)**
- **minor bug fixes + quantity styling**
- **quantity bubble size increased**
=> styling fix

src/components/Visitor Components/MenuDetail.jsx
- **add on requested changes done**
- **price reflection without size - fixed**
=> bug fix for cart price
